### ISSUE TITLE
Suggestions for assiginR packages

### ISSUE THREAD

**Issue by Otoliths** [SPATIAL-Lab/assignR#18]
Dear SPATIAL-Lab,

Congratulations on your team's assiginR package being published in the Methods in Ecology and Evolution. The _assiginR_ is very very nice R package, stable isotopes of O and H in water are meaningful indicators of aquatic food webs and fish migrations. 

Suggestions:
1. Can you add the Global Network of Isotopes in Rivers (GNIR) dataset to this package? Or other public isotopic datasets (e.g., C, Sr isotopes)
2. For the convenience of users, can users add isotope values for tissues of known origin according to research requirements? How can a user create a dataset similar to knownOrig?

References
https://www.iaea.org/services/networks/gnir
Nan, Y., Tian, F., Hu, H., Wang, L., & Zhao, S. (2019). Stable Isotope Composition of River Waters across the World. Water, 11(9),1760.

**Comment by bumbanian** [comment]
Hi there...thanks for your comments and suggestions!

1. Unfortunately the IAEA isotope hydrology group does not have a standard or formal license governing the use of the data they have compiled in the GNIP and GNIR databases, and we (and others) have been told when we asked that they will not allow 3rd party redistribution of these data. In other words we are not allowed to include them with the package. Moreover, in order to use such data in assignR you'd need to turn them into an isoscape model, which is not part of the functionality of the package. We have developed other tools for isoscape modeling for certain systems (e.g., http://isomap.org) and also have published and freely shared other isoscapes (including for USA rivers) here: http://wateriso.utah.edu/waterisotopes/pages/data_access/ArcGrids.html. We're currently in the process of adding additional published isoscapes for C and Sr to IsoMAP, and will be writing a connector in assignR that allows users to pull these directly from IsoMAP via a new API for that resource. Lastly, there are several efforts ongoing to develop FAIR databases for isotope data that we hope assignR will link to in the future, including http://waterisotopesDB.org and http://isobank.org.
2. Absolutely! The format of the data object extracted from knownOrig is described in the manual page for subOrigData(), it is just a SpatialPointsDataFrame where the dataframe part includes only one field that contains the isotope value for the sample (as a warning, we are working to an update that may change this formatting, but you can always refer to the manual page in the version of the package you're using for details. You can very easily read your own data into R and convert them to this format, then use them in the other functions.
